import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex flex-row justify-evenly p-4 bg-transparent shadow-md">
          <div className="flex flex-row space-x-10 md:space-x-24 self-center text-black backdrop-blur-3xl">
            <div>
              <Link href="/sedes" className="font-bold text-md">
                Posición
              </Link>
            </div>
            <div>
              <Link href="/" className="font-bold text-md">
                Inicio
              </Link>
            </div>
          </div>
        </nav>
        {children}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>
      </body>
    </html>
  );
}
